# Generated by Django 5.2.2 on 2025-06-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='github_link',
        ),
    ]
